FROM elixir:1.12.2

# Install pg client for db setup
RUN apt-get -qqq update && \
    apt-get install -qqq -y postgresql-client inotify-tools nodejs npm

RUN npm install -g npm@latest

# Create app directory and copy the Elixir project into it
RUN mkdir /app
WORKDIR /app

RUN groupadd -g 1000 juntos && \
    useradd -m -s /bin/bash -r -u 1000 -g juntos juntos
# Install hex package manager
USER juntos
RUN mix local.hex --force
RUN mix local.rebar --force

USER root
CMD ["/app/scripts/entrypoint-dev.sh"]
